apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-coordinator-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- toYaml (merge (.Values.coordinator.env | default dict) (.Values.sharedEnv | default dict)) | nindent 2 }}
