apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- toYaml (merge (.Values.worker.env | default dict) (.Values.sharedEnv | default dict)) | nindent 2 }}
