authentik:
  secret_key: null # VT_META_AUTHENTIK_SECRET
  error_reporting:
    enabled: false
  postgresql:
    password: null # VT_META_AUTHENTIK_POSTGRES_PASSWORD

server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: null # Computed
    enabled: true
    hosts: null # VT_META_AUTHENTIK_HOST
    tls:
      - hosts:
          - null # VT_META_AUTHENTIK_HOST
        secretName: null # Computed
    ingressClassName: nginx

postgresql:
  enabled: true
  auth:
    password: null # VT_META_AUTHENTIK_POSTGRES_PASSWORD
