apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    profile: tlsserver
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
